// src/database/seeds/synthetic-consent.ts
//
// Consent for SEEDED TEST USERS ONLY. Consent is legal evidence, so this data is
// deliberately, unmistakably fake: the text says so, the IP is loopback. Never
// run this against real users — for those, record real consent events through
// POST /api/v1/users/:userId/consents.

export const SYNTHETIC_CONSENT_TEXT =
  'SYNTHETIC TEST CONSENT — generated by the development seed script. Not a real user consent.';

/** One append-only OPT_IN per consent-requiring channel. */
export const syntheticConsentRows = (userId: string) =>
  [
    { channel: 'sms', consentType: 'OPT_IN' },
    { channel: 'email', consentType: 'OPT_IN' },
    { channel: 'whatsapp', consentType: 'WHATSAPP_OPT_IN' },
  ].map((c) => ({
    userId,
    ...c,
    granted: true,
    consentText: SYNTHETIC_CONSENT_TEXT,
    ipAddress: '127.0.0.1',
    userAgent: 'seed-script',
  }));
