// scripts/export-openapi.ts
//
// Generates docs/api-specification.{json,yaml} from the running code's own
// Swagger metadata, so the API docs cannot drift from the controllers.
//
//   npm run docs:openapi            # regenerate
//   npm run docs:openapi -- --check # exit 1 if the committed files are stale (CI)
//
// Builds the application module graph WITHOUT connecting to any infrastructure
// (providers are constructed, lifecycle hooks are not run).
// eslint-disable-next-line @typescript-eslint/no-require-imports
require('dotenv').config({
  path: require('path').resolve(process.cwd(), '.env'),
});

import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { stringify } from 'yaml';
import { AppModule } from '../src/app.module';
import { configureApp } from '../src/app.setup';

export async function buildOpenApi(): Promise<Record<string, unknown>> {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(),
    { logger: false },
  );
  configureApp(app);

  const config = new DocumentBuilder()
    .setTitle('WealthBridge Notification Engine')
    .setDescription(
      'Event-driven notification system for financial services — 25 event types, ' +
        '5 delivery channels, TRAI/NCC DND compliance, consent management, digests. ' +
        'Requests and responses are snake_case; errors use { error, message, details, request_id }.',
    )
    .setVersion('1.0.0')
    .addServer('http://localhost:3000', 'Local development')
    .addBearerAuth(
      { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      'JWT',
    )
    .build();

  const doc = SwaggerModule.createDocument(app, config) as unknown as Record<
    string,
    unknown
  >;
  await app.close().catch(() => undefined);
  return doc;
}

async function main(): Promise<void> {
  const doc = await buildOpenApi();
  const json = JSON.stringify(doc, null, 2) + '\n';
  const yaml =
    '# GENERATED by `npm run docs:openapi` — do not edit by hand.\n' +
    stringify(doc);

  if (process.argv.includes('--check')) {
    const stale = [
      'docs/api-specification.json',
      'docs/api-specification.yaml',
    ].filter(
      (f, i) =>
        !existsSync(f) || readFileSync(f, 'utf8') !== (i === 0 ? json : yaml),
    );
    if (stale.length) {
      console.error(
        `✗ stale API docs: ${stale.join(', ')} — run \`npm run docs:openapi\``,
      );
      process.exit(1);
    }
    console.log('✓ API docs are up to date');
    process.exit(0);
  }

  writeFileSync('docs/api-specification.json', json);
  writeFileSync('docs/api-specification.yaml', yaml);
  console.log(
    `✓ wrote docs/api-specification.{json,yaml} (${Object.keys((doc.paths as object) ?? {}).length} paths)`,
  );
  process.exit(0); // infrastructure clients created by providers keep the loop alive
}

if (require.main === module) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
